### PR TITLE
Twig 1.27+ support

### LINKED ISSUE #291: FatalErrorException in Loader.php
`Class TwigBridge\Twig\Loader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceContext)`

It throws for 0.9.2 and 0.9.3 versions.

### PR DESCRIPTION
**Pull request by SCIF**
Fixed some deprecations and limited min version of twig 1.27+. Should fix #291.Replaces #290.

### CODE REVIEW

File: src/Engine/Twig.php [hunk 1]
```diff
@@ -105,7 +105,7 @@ public function get($path, array $data = [])
      */
     protected function handleTwigError(Twig_Error $ex)
     {
-        $templateFile = $ex->getTemplateFile();
+        $templateFile = $ex->getSourceContext()->getPath();
```
Comment (barryvdh) [inline src/Engine/Twig.php]: Is this possible for all exceptions?

**Comment by brunogaspar** [comment]
This PR broke the package, at least for me.

```php
Type error: Argument 1 passed to Twig_Loader_Chain::addLoader() must implement interface Twig_LoaderInterface, instance of TwigBridge\Twig\Loader given, called in /../app/vendor/twig/twig/lib/Twig/Loader/Chain.php on line 30
```

twig/twig: v1.30.0
rcrowe/TwigBridge: dev-master fda1efa

**Comment by barryvdh** [comment]
Rwveeted
